# Generated by Django 3.2.9 on 2022-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('itemCode', models.IntegerField()),
                ('itemName', models.CharField(max_length=1000)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
