# Generated by Django 3.2.9 on 2022-01-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220115_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
