# Generated by Django 3.2.9 on 2022-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.BooleanField(default=True),
        ),
    ]
