# Generated by Django 3.2.9 on 2022-01-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='income',
        ),
    ]
