# Generated by Django 3.2.9 on 2022-01-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.IntegerField(unique=True)),
                ('itemName', models.CharField(max_length=1000)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
