# Generated by Django 3.2.9 on 2022-01-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_expense_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='billnumber',
        ),
    ]
