# Generated by Django 3.2.9 on 2022-01-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
            ],
        ),
    ]
